### PR TITLE
added nicmos unit conversion notebook

### PR DESCRIPTION
**Pull request by shannnnnyyy**
I added a notebook on programmatic wats to perform unit conversions as provided by http://www.stsci.edu/hst/nicmos/tools/conversion_form.html. I put this notebook in a new directory NICMOS, so that any future NICMOS notebooks can be added there as well.

### CODE REVIEW

**Comment by pllim** [comment]
Please do the following:

1. Remove `._nicmos_unit_conversion.ipynb` from version control.
2. Add `._*.ipynb` to the existing `.gitignore` file.
3. Squash your commits into one. This is necessary so that `._nicmos_unit_conversion.ipynb` never existed in `git` history.

Thanks!

**Comment by pllim** [comment]
You might also want to consider adding a few more examples that are useful from the INS standpoint. The one I provided originally was a quick prototype.

**Comment by shannnnnyyy** [comment]
@pllim can this be merged? seems like someone might want to use this according to the discussion on slack?

**Comment by shannnnnyyy** [comment]
ugh, i did something wrong when trying to squash and now all these irrelevant commits are in here. how can i fix this?

**Comment by pllim** [comment]
Thanks, @shannnnnyyy !

**Pull request merged**
