### PR TITLE
MAST: Adding TASC light curve notebook

### PR DESCRIPTION
**Pull request by ceb8**
Turned my TASC presentation notebook into an example notebook.

Works through getting TASC light curves from MAST using astroquery, using tesscut to make cutouts, and overplotting TIC sources.

### CODE REVIEW

**Comment by ceb8** [comment]
@eteq @obviousrebel Usually I review and merge MAST notebooks PRs, however since I'm the one who make this PR I'm not sure what the procedure should be. I had @mustaric look at it and implemented her suggestions, is that a sufficient review or should one of you also review it?

**Comment by mustaric** [comment]
What is the status of this notebook. I'd like to advertise it in the Newsletter this month.  Can it be pushed? @eteq @obviousrebel @ceb8

**Comment by pllim** [comment]
`@obviousrebel` is no longer maintaining the infrastructure of this project. FYI.

**Comment by ceb8** [comment]
@pllim Who has taken his place?

**Comment by pllim** [comment]
@ceb8, as Arya puts it, "No one." :grimacing:

**Comment by ceb8** [comment]
OK than I am going to call this PR good and merge it.

**Pull request merged**
