### PR TITLE
Improving the build process for Notebooks

### PR DESCRIPTION
**Pull request by jbcurtin**
The goal of this Pull Request is to help improve the build process for jupyter notebooks being created here in this repository

### Rendered Example
old: https://spacetelescope.github.io/notebooks/
new: https://jbcurtin.github.io/notebooks/
### Reduced build time
The build has been reduced from 2+hours to less than 30 minutes. There is still room to improve the build and reduce the builds even more

### Every notebook lives in its own world
When a notebook is rendered, `pre_requirements.txt` is installed in an isolated environment followed by `requirements.txt`. This allows packages like `astroquery` to be installed after `numpy` because `numpy` is required for the installation

### Improved Error Propagation
When clicking into the build process, a log is generated with all the build errors including warnings. There is still room for improvement here. One of the next steps is to fail the pipeline if any error occurs in a new notebook being added through a Pull Request

### Conda Dependency
We'll eventually be able to remove conda as a dependency to build notebooks

@pllim and @eteq , please be very vocal about further improvements you'd like to see. I plan to refine this over the next few weeks and I need input from the community to know how to support it!

### CODE REVIEW

**Comment by pllim** [comment]
Wait a minute. Are "pages" supposed to be version controlled? I thought they would be generated on-the-fly, no? `+856,079 −45` seems a little scary.

**Comment by jbcurtin** [comment]
The `pages/` directory can be taken out of the `master` branch, but for the static site to render the html at `https://spacetelescope.github.io/notebooks/`, it'll have to be included. ( all I did was change the rendering location )

**Comment by pllim** [comment]
Yeah, please leave the generated content out of `master` branch. Thanks!

**Comment by pllim** [comment]
@jbcurtin , any chance you can squash all the commits so that `pages` doesn't appear in the history of `master`? Thanks!

**Comment by eteq** [comment]
More later on this, but @jbcurtin, do you think you can add back in the CircleCI stage that prints the path to the artifacts? You can see an example of back when it was working here: https://circleci.com/gh/spacetelescope/notebooks/82?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link - the very last build stage there just gives a convenient link to follow to check the artifacts. (Which is otherwise difficult for random-contributor to reconstruct)

**Comment by jbcurtin** [comment]
yeah, the stage can be added back

**Pull request closed without merging**
