### PR TITLE
Adding eight new tutorials under `MAST/Kepler`

### PR DESCRIPTION
**Pull request by barentsen**
This PR proposes to add eight new Kepler-focused tutorial notebooks under `notebooks/MAST/Kepler`.

These new notebooks have the following titles:
1. Using Kepler Light Curve Products with Lightkurve
2. Using Kepler Target Pixel File Products with Lightkurve
3. Plotting Kepler Target Pixel File Products with Lightkurve
4. Combining Multiple Quarters of Kepler Data with Lightkurve
5. Creating Your Own Light Curves using Custom Aperture Photometry
6. Verifying the Location of a Signal in Kepler Pixel Data
7. Creating Periodograms and Identifying Significant Peaks
8. Measuring and Removing a Rotation Period Signal from a Kepler Light Curve

These tutorials were authored by @ojhall94 & @astrobel, and have already been peer-reviewed once by @mustaric & @barentsen.  They have also been copy-edited by @lglattly with assistance from @kelle.  In other words, these notebooks should be in a good shape, however we warmly welcome any and all suggestions for improvements!

I anticipate opening a second pull request later this month with an additional 8-12 Kepler notebooks, which will focus on more advanced data analysis topics (including systematic noise identification, systematic noise removal, and asteroseismology).

### CODE REVIEW

**Comment by barentsen** [comment]
The `circleci` continuous integration is reporting 11 test failures.  None of the failures appear to be related to the new notebooks added by this PR.  Instead, the following existing notebooks appear to be failing:
* Initialization
* K2_Lightcurve
* K2_TPF
* interm_tesscut_dss_overlay
* interm_tess_prf_retrieve
* PSF_phot_01
* Kepler_DVT
* nicmos-unit-conversion
* mask_satellite
* K2_FFI
* beginner_how_to_use_ffi

The failures are predominantly due to trivial typos in the `requirements.txt` files. I opened a separate PR (#145) with a number of fixes.

**Comment by barentsen** [comment]
I rebased on master to confirm that the only notebook which is now failing the CircleCI tests is `DrizzlePac/Initialization`, which is not related to the Kepler notebooks added by this PR.

Screenshot_20200923-125910

As a result, I believe this PR can be merged. /cc @mustaric

**Comment by mustaric** [comment]
These notebooks are part of the Kepler/NumFocus work and are part of the MAST Kepler-Close-out.  I have read them and think they are a great addition to the spacetelescope notebooks repository.

**Review by pllim — APPROVED** [review]
Also failed on "make pages" but I have no idea what that means. We can worry about that later.

Thanks!

**Pull request merged**
