### PR TITLE
DrizzlePac: Sort inputs before pass into TweakReg

### PR DESCRIPTION
**Pull request by pllim**
Attempt to fix CI failure that is plaguing other unrelated PRs.

### CODE REVIEW

**Comment by pllim** [comment]
OMG... `KeyError: "Extension ('D2IMARR', 1.0) not found."`

I give up.

**Comment by samanthalh** [comment]
We ran into this problem in the sparse field notebook and actually created an input_flc.list file (https://github.com/spacetelescope/notebooks/blob/master/notebooks/DrizzlePac/align_sparse_fields/input_flc.list), added that to the repo with the specific FLC file we wanted as the reference at the top of the list file. The code looked something like this: 

tweakreg.TweakReg('@input_flc.list',
                  imagefindcfg={'threshold': 100,'conv_width': 3.5},
                  shiftfile=True, outshifts='shift814_flc_test1.txt',
                  updatehdr=False, interactive=False, ylimit=0.4)

This way no matter how the stupid sorting order changed in glob or python, the notebook would NOT break. 

I would try that first, but I'm worried the error you got is something else entirely.

**Comment by pllim** [comment]
@samanthalh , can you or someone else who wrote this originally submit a new PR with your suggested change of using a `lis` file? I am not a DrizzlePac user, so I don't even know how to order those files in the `lis`. Thanks!

**Comment by samanthalh** [comment]
Yes, we can do that! I would have suggested it, in fact, but it seemed like something you needed fixed immediately, and we all have other duties :)

**Comment by pllim** [comment]
Yes, understood. If it will take a while, then I would go ahead and exclude it (again) from CI so it doesn't hold up other PRs.

FWIW, here is the TweakReg log:

```
[INFO    ] Setting up logfile :  tweakreg.log
[INFO    ] TweakReg Version 1.4.7(18-April-2018) started at: 18:25:28.097 (20/03/2019) 
[INFO    ] 
[INFO    ] Version Information
[INFO    ] --------------------
[INFO    ] Python Version [GCC 7.3.0]
[INFO    ] 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[INFO    ] numpy Version -> 1.15.4 
[INFO    ] astropy Version -> 3.1.2 
[INFO    ] stwcs Version -> 1.4.2 
[INFO    ] 
[INFO    ] USER INPUT PARAMETERS common to all Processing Steps:
[INFO    ] 	clean :	False
[INFO    ] 	enforce_user_order :	True
[INFO    ] 	exclusions :	
[INFO    ] 	expand_refcat :	False
[INFO    ] 	input :	['j9irw3fwq_flc.fits', 'j9irw4b1q_flc.fits', 'j9irw5kaq_flc.fits']
[INFO    ] 	interactive :	False
[INFO    ] 	refimage :	
[INFO    ] 	runfile :	tweakreg.log
[INFO    ] 	updatewcs :	False
[INFO    ] 	verbose :	False
[INFO    ] 	writecat :	True
[INFO    ] 
[INFO    ] Finding shifts for: 
[INFO    ]     j9irw3fwq_flc.fits
[INFO    ]     j9irw4b1q_flc.fits
[INFO    ]     j9irw5kaq_flc.fits
[INFO    ] 
[INFO    ] USER INPUT PARAMETERS for finding sources for each input image:
[INFO    ] 	clean :	False
[INFO    ] 	computesig :	True
[INFO    ] 	conv_width :	3.5
[INFO    ] 	dqbits :	
[INFO    ] 	enforce_user_order :	True
[INFO    ] 	expand_refcat :	False
[INFO    ] 	fluxmax :	None
[INFO    ] 	fluxmin :	None
[INFO    ] 	input :	['j9irw3fwq_flc.fits', 'j9irw4b1q_flc.fits', 'j9irw5kaq_flc.fits']
[INFO    ] 	interactive :	False
[INFO    ] 	nsigma :	1.5
[INFO    ] 	peakmax :	None
[INFO    ] 	peakmin :	None
[INFO    ] 	ratio :	1.0
[INFO    ] 	refimage :	
[INFO    ] 	roundhi :	1.0
[INFO    ] 	roundlo :	-1.0
[INFO    ] 	runfile :	tweakreg.log
[INFO    ] 	sharphi :	1.0
[INFO    ] 	sharplo :	0.2
[INFO    ] 	skysigma :	0.0
[INFO    ] 	theta :	0.0
[INFO    ] 	threshold :	4.0
[INFO    ] 	updatehdr :	False
[INFO    ] 	updatewcs :	False
[INFO    ] 	use_sharp_round :	False
[INFO    ] 	verbose :	False
[INFO    ] 	writecat :	True
[INFO    ] 	xyunits :	pixels
[INFO    ] 
[WARNING ] /opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/io/fits/file.py:379: AstropyUserWarning: File may have been truncated: actual file length (31181984) is smaller than the expected size (33595200)
  .format(self.size, pos), AstropyUserWarning)

[INFO    ] Trailer file written to:  tweakreg.log
[ERROR   ] An unhandled exception ocurred:
Traceback (most recent call last):
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/drizzlepac/util.py", line 218, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/drizzlepac/tweakreg.py", line 308, in run
    **catfile_kwargs)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/drizzlepac/imgclasses.py", line 99, in __init__
    wcsextn = util.findWCSExtn(filename)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/drizzlepac/util.py", line 551, in findWCSExtn
    refwcs = wcsutil.HSTWCS('{}[{}]'.format(rootname,i))
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/stwcs/wcsutil/hstwcs.py", line 147, in __init__
    key=self.wcskey)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 457, in __init__
    det2im = self._read_det2im_kw(header, fobj, err=minerr)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 780, in _read_det2im_kw
    d_data = fobj[str('D2IMARR'), d_extver].data
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 300, in __getitem__
    self._positive_index_of(key))
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 754, in _positive_index_of
    index = self.index_of(key)
  File "/opt/conda/envs/notebooks_env/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 735, in index_of
    raise KeyError('Extension {!r} not found.'.format(key))
KeyError: "Extension ('D2IMARR', 1.0) not found."
[ERROR   ] Invalid alias: The name clear can't be aliased because it is another magic command.
[ERROR   ] Invalid alias: The name more can't be aliased because it is another magic command.
[ERROR   ] Invalid alias: The name less can't be aliased because it is another magic command.
[ERROR   ] Invalid alias: The name man can't be aliased because it is another magic command.
```

**Comment by catherine-martlin** [comment]
Hey @pllim - I'll take a look and try to update this in the next day or two around my schedule. Thank you for the logs! Hopefully it'll be a quick fix. Would it be better for workflow for me to work on this PR/branch or should I make a different one?

**Comment by pllim** [comment]
@catherine-martlin , thanks! It would be easier if you work on your own branch on your own fork. I'll just close this PR now.

**Pull request closed without merging**
