### PR TITLE
Updated email address for Oliver Hall

### PR DESCRIPTION
**Pull request by ojhall94**
The email address in the new tutorials that I wrote was outdated (whoops), so I've updated them to my new one.

### CODE REVIEW

**Comment by ojhall94** [comment]
I was told to tag @mustaric :)

**Review by pllim — CHANGES_REQUESTED** [review]
There are other changes unrelated to email change. I would suggest you do a simple plain text search and replace for updating just the email. Thanks!

**Comment by ojhall94** [comment]
Hows this? :)

**Review by pllim — APPROVED** [review]
Much better. Thanks! Since you pinging @mustaric , I'll wait for her approval before merge.

**Comment by mustaric** [comment]
These changes look good to me.  Thanks for updating your contact info, @ojhall94.

**Pull request merged**
