### PR TITLE
Cleanup TravisCI references

### LINKED ISSUE #49: Travis CI is broken?
The deploy portion of https://travis-ci.org/spacetelescope/notebooks/builds/476275730 shows a red status, as a result the whole project CI status is red. 

Also see https://jira.stsci.edu/browse/JUSI-24

### PR DESCRIPTION
**Pull request by obviousrebel**
Removed .travis.yml, updated status badge to circleCI in readme.

EDIT: Close #49

### CODE REVIEW

**Comment by pllim** [comment]
I don't see CircleCI run for this PR, is that expected?

**Comment by obviousrebel** [comment]
> I don't see CircleCI run for this PR, is that expected?

@pllim I just turned it on to build PRs, I believe it should now.

**Comment by pllim** [comment]
Any chance to do a force push here to see for sure?

```
git commit --amend
(Do some superficial edit to commit message, like adding a period.)
git push -f origin branch_name
```

**Comment by pllim** [comment]
OK I see CircleCI running on the other PR, so merging this as is. Thanks!

**Pull request merged**
