### PR TITLE
updating notebook

### PR DESCRIPTION
**Pull request by cshanahan1**
Changes to the notebook that demonstrates how to align and drizzle images from multiple visits.

1. Changed an example that was demonstrating how to run tweakreg with default parameters, but found too many sources and used too much memory. I left this in but commented it out and added some commentary about why it will crash and the importance of adjusting source finding parameters.

2. removed ccdproc import, it was only being used in one cell to look at the PA_V3 of each input file, and you can just inspect the file headers to get this info for the same number of lines.

3. Removed an example that was showing the necessity of adjusting 'searchrad' for this dataset. I guess based on some updates to tweakreg, the default searchrad of 1 is now fine for this data. I added some commentary about the cases when a user might want to adjust this value.

4. Some more text changes that reflect changes to tweakreg/drizzle since this notebook was written.

### CODE REVIEW

**Comment by cshanahan1** [comment]
@eteq can you tag mihai?

**Comment by pllim** [comment]
@mcara (won't let me assign him as reviewer)

**Comment by mcara** [comment]
@pllim Of course you can.

**Comment by pllim** [comment]
I mean, I literally cannot. See screenshot. 😸 

Screenshot 2022-01-19 154538

**Comment by mcara** [comment]
@pllim

@larrybradley was also in the same sprint.

**Comment by pllim** [comment]
I didn't even know this is a Sprint... Ping whoever is relevant then. _Backs away..._

**Comment by mcara** [comment]
no, the sprint was 4 years ago or so

**Comment by larrybradley** [comment]
It's because @mcara is not a repo maintainer (he can't merge PRs).

**Review by mcara — APPROVED** [review]
Modified notebook run successfully.

**Comment by pllim** [comment]
@cshanahan1 , do you want to update the "date updated" at the bottom?

**Review by pllim — APPROVED** [review]
I am approving by proxy. I have the utmost confidence in Mihai's review.

Thanks for fixing this, Clare!

**Comment by pllim** [comment]
Wouldn't worry about the CI. I don't think it has ever passed.

**Comment by mcara** [comment]
>I have the utmost confidence in Mihai's review.

**Comment by mcara** [comment]
> I have the utmost confidence in Mihai's review.

Don't!!!

**Pull request merged**
