### PR TITLE
Adding logos for footers

### PR DESCRIPTION
**Pull request by arfon**
/ cc @pllim

### CODE REVIEW

**Comment by pllim** [comment]
Do you plan to address the rest of the issue of deleting duplicate logo files and make all the notebooks use this one? 😉 🙏

**Comment by arfon** [comment]
Sure thing. Let's merge this and I'll open a subsequent PR with the fixes to the existing notebooks?

**Comment by pllim** [comment]
I don't think we need both PNG and SVG? Given #54, perhaps we should just keep the PNG. Add one PNG, deleting the other 14 PNGs and several more SVGs seems like a good trade-off.

**Comment by arfon** [comment]
OK, just the PNG now in this PR.

**Pull request merged**
