### PR TITLE
y'all had a deg when you meant arcsec in one of the statements

### PR DESCRIPTION
**Pull request by benmontet**
In the HD 209458 notebook the search query found the TIC object was 0.17 arcsec from the resolved coordinates for 209, but it was listed as deg in the notebook print statement.

### CODE REVIEW

**Comment by pllim** [comment]
@benmontet , please clear the output of the notebook.

@ceb8 , please review the unit correction.

**Comment by benmontet** [comment]
Sure, no problem; I've removed the output from the notebook and re-pushed.

**Comment by ceb8** [comment]
Seems correct, but @scfleming should look at it since it was his notebook originally.

**Comment by ceb8** [comment]
@benmontet You are going to need to squash your commits to get rid of the noteboook output in the history. Directions here: https://github.com/spacetelescope/notebooks/blob/master/CONTRIBUTING.md#squashing-or-what-to-do-if-you-accidentally-committed-data

**Comment by scfleming** [comment]
Confirmed, this was a mistake and should be fixed. Thanks @benmontet !

**Comment by eteq** [comment]
I love that "y'all" is in a PR title.  That is all.

**Pull request merged**
